language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
env:
  - IPYTHON_VERSION=">1.0,<2.0"
  - IPYTHON_VERSION=">2.0"
install:
  - pip install ipython$IPYTHON_VERSION
script: 
  - python setup.py test
matrix:
  exclude:
    - python: "2.6"
      env: IPYTHON_VERSION=">2.0"
    - python: "3.2"
      env: IPYTHON_VERSION=">2.0"

